### ISSUE TITLE
Logo for Comedy Companion

### ISSUE THREAD

**Issue by dereksweet** [g-harel/open-source-logos#2]
## The Comedy Companion
> https://github.com/dereksweet/ComedyCompanion

### Background
React Native application for comedians to manage their jokes, set lists, and shows. 

### Description
I would love a little character like the Reddit alien to go with the project. Something rather simple with black and white for the most part with tiny splashes of colour. I was envisioning a little devil, as opposed to an alien, with a big microphone nearly the size of his body in front of him. 

### Time Constraints
No time constraints at all. Would like to release the app soon but am in no real rush to do so. The whole app is pretty much finished, just need to add a splash page, logo, and app icon. If you are able to just draw the character I can probably do the rest as I'm quite proficient with fonts and such, just a terrible artist. If you do actually want to make me a complete logo that could be used for the splash page the full app name is "The Comedy Companion".

**Comment by g-harel** [comment]
Ok here is a first pass, tell me what you think!

The second one is a play on the XD emoticon with some added apostrophes for the horns (thought it was cool so I couldn't resist doing it).

![image](https://cloud.githubusercontent.com/assets/9319710/26525118/188fec4c-431b-11e7-8644-8af02fc94c4e.png)

**Comment by dereksweet** [comment]
Hey man sorry for the delays getting back to you. The one on the left is great! Are you able to complete the concept I had of him standing behind a microphone nearly the size of his body? Nothing screams stand up comedy like a microphone. I was kind of envisioning him as being the little devil that sits on your shoulder, hence The Comedy Companion.

**Comment by g-harel** [comment]
I was thinking of just replacing the usual pitchfork with a microphone stand, am I understanding correctly ?

**Comment by dereksweet** [comment]
I drew up a very quick and insanely bad drawing of what I was thinking. :) Here it is.. 

![img_4080 2](https://cloud.githubusercontent.com/assets/955108/26596406/d5692290-452b-11e7-9702-e872c239fbe7.JPG)

So the idea is he's the little devil that sits on your shoulder, you know the one I mean? Like an angel and a devil on each shoulder type idea? But he's holding a microphone.

**Comment by g-harel** [comment]
Ok, that makes it a lot more clear!

**Comment by g-harel** [comment]
![image](https://cloud.githubusercontent.com/assets/9319710/26612672/62317b20-4584-11e7-8ec3-60dbaf69e139.png)

**Comment by dereksweet** [comment]
Haha! DUDE I love it!! That is so perfect! Great work!

**Comment by dereksweet** [comment]
I will use the first graphic you did as the app icon, then the full picture as the logo. Man just great work, thanks so much!

**Comment by g-harel** [comment]
I'm glad you like it! 

I've added the images [here](https://github.com/g-harel/open-source-logos/tree/master/projects/The%20Comedy%20Companion/images)
