### ISSUE TITLE
Escobot

### ISSUE THREAD

**Issue by pbgnz** [g-harel/open-source-logos#7]
## Escobot
> https://github.com/pbgnz/tellme

### Background
It's a basic slack bot. I am planning on refactoring and adding new features. A good start would be changing the name and finding a cool logo for the project and slack icon.

### Description
The slack bot is gonna be Pablo Escobar themed. So I have two ideas in mind, you can pick the one that you like the most or the one that will be easier for you;

1- The first design I have in mind is to have a cartoonish Escobar dressed like a butler. Basically, I want something similar to the [Jenkins logo](https://wiki.jenkins.io/download/attachments/2916393/logo.png?version=1&modificationDate=1302753947000&api=v2) but with Escobar.

2- The second design I have in mind is a cartoonish light airplane flying in the sky and dropping a crate. To be more precise, the light airplane model is the [HK-617](https://www.jetphotos.com/photo/6413786) and the design could look something similar to [this](https://static.vecteezy.com/system/resources/previews/000/128/420/non_2x/free-cessna-watercolor-background-vector.jpg).

### Time Constraints
No time constraints.

**Comment by g-harel** [comment]
I don't have any of the apps I used to use on ubuntu, so I'm not sure when I'll be able to do this.

I like the jenkins idea, I don't think a plane dropping something would be understandable on the scale of an icon.

**Comment by pbgnz** [comment]
Sure, take your time!

The Jenkins idea it is then.

**Comment by pbgnz** [comment]
Hi,
I forgot that I opened this issue. What's your status on this ?

**Comment by g-harel** [comment]
No progress, I looked a while back and didn't see any activity so I thought you had abandoned the project!

**Comment by pbgnz** [comment]
I did abandon the project,
so I guess you can close this issue!

**Comment by pbgnz** [comment]
I changed my mind; I still need the Escobar logo!
The new [Jenkins X logo](https://www.google.com/search?q=jenkins+x&client=ubuntu&hs=GXs&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj007zesprdAhVnmeAKHbKXCeIQ_AUICygC&biw=1863&bih=951#imgrc=1OlGVzjHjOYnnM:) looks like a good example of what I want
